name: Build and Deploy

on:
    push:
        branches : 
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm run prod
            
            - name: Upload to Server
              uses: SamKirkland/FTP-Deploy-Action@4.0.0
              with:
                server: ${{secrets.SERVER}}
                username: ${{secrets.USERNAME}}
                password: ${{secrets.PASSWORD}}
                local-dir: ./www/
                server-dir: /public_html/apps/generateur-de-nom/